// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0OgtUXjtQtJmumDY4COurPCRpqR_5w8',
    appId: '1:433046477539:web:2b27ccbb6d86b2293483d6',
    messagingSenderId: '433046477539',
    projectId: 'final-project-fa0ea',
    authDomain: 'final-project-fa0ea.firebaseapp.com',
    storageBucket: 'final-project-fa0ea.firebasestorage.app',
    measurementId: 'G-VWR1RFBLPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fiuSn7ZXWum_tLAgz0Qk4-d-wd4yamQ',
    appId: '1:433046477539:android:20d0a3b84fb3163f3483d6',
    messagingSenderId: '433046477539',
    projectId: 'final-project-fa0ea',
    storageBucket: 'final-project-fa0ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtYbB2ZauA4U5Se0Z_t7qTaM2RA_a0-s',
    appId: '1:433046477539:ios:ebd968e2bb1661a23483d6',
    messagingSenderId: '433046477539',
    projectId: 'final-project-fa0ea',
    storageBucket: 'final-project-fa0ea.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtYbB2ZauA4U5Se0Z_t7qTaM2RA_a0-s',
    appId: '1:433046477539:ios:ebd968e2bb1661a23483d6',
    messagingSenderId: '433046477539',
    projectId: 'final-project-fa0ea',
    storageBucket: 'final-project-fa0ea.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo0OgtUXjtQtJmumDY4COurPCRpqR_5w8',
    appId: '1:433046477539:web:5f3ef8c974361b073483d6',
    messagingSenderId: '433046477539',
    projectId: 'final-project-fa0ea',
    authDomain: 'final-project-fa0ea.firebaseapp.com',
    storageBucket: 'final-project-fa0ea.firebasestorage.app',
    measurementId: 'G-RWPZRJWCD5',
  );
}
